### PR TITLE
Add extra query string option in params for Service.request method.

### PR DESCRIPTION
**Pull request by artur79**
You may need to insert extra query string for example when trying to register participant to an event which has some extra registration questions. Like described here

http://www.connectusers.com/tutorials/2013/09/event_registration_using_adobe_connect_apis/index.php

http://YOURSERVER.adobeconnect.com/api/xml? action=event-register&sco-id=1227409411& login=john@d.com&password=1234& password-verify=1234&first-name=John& last-name=Doe&interaction-id=122558421& response=Doe%20Inc& interaction-id=1227230451&response=6-10

Notice that interaction-id key is used more than once, so can not use params hash, thus I've added that extra param.

### CODE REVIEW

**Comment by sbleon** [comment]
One more question: I think right now you to have to prefix your `extra_query_string` with `&`. We could add that automatically. Is that a better API?

**Comment by sbleon** [comment]
@artur79 are you still interesting in getting this merged? I have one open question (about the manual `&`).

**Comment by artur79** [comment]
@sbleon version bump is reverted

**Comment by artur79** [comment]
I am not sure if it's necessary. I use that extra query string for interactions param, for which order is important (stupid Adobe API 👎 ). Those are couples of params, first interaction id and than it's value, e.g:
  
>   {1314062850 => 'Both', 1314081462 => 'Foo Corp'}

And on my side I create extra query string like:
```
   if interactions && interactions.any?
      extra_query_string = ''
      interactions.each do |key, value|
        extra_query_string += "&interaction-id=#{key}&response=#{URI.encode(value)}"
      end
      params[:extra_query_string] = extra_query_string
    end
```

**Comment by sbleon** [comment]
OK. If the library isn't going to prepend the ampersand, we should add a
check to make sure the caller has included it. Something like:
```
if extra_query_string.present? && !extra_query_string.start_with?('&')
  raise "Invalid argument. extra_query_string should start with &."
end
```

**Comment by artur79** [comment]
I've added related commit

**Pull request merged**
