### PR TITLE
Prevent error when retrieving 'my-meetings' folder

### PR DESCRIPTION
**Pull request by Rodel30**

### CODE REVIEW

**Comment by sbleon** [comment]
@zachpendleton can you review this and maybe make a new release? We'd love to get back on an official gem release. Thanks!

**Comment by sbleon** [comment]
Hi, @zachpendleton. Please let us know if you're planning to review this PR. If you're unable to, perhaps you'd be interested in making @rodel30 and I committers so we can merge it and make a new release.

I would be very unhappy if we had to release our fork under a new name! :cry:

**Comment by zachpendleton** [comment]
Thanks for reaching out and sorry for not being more attentive; I'm adding you both as committers so that you'll be able to continue work on the gem moving forward. I appreciate all of your work on the project and hate that it's been such a hassle for you.

**Comment by sbleon** [comment]
Thanks, Zach! We’re on it!

For us to be able to release new gem versions, I think we need you to run:

gem owner adobe_connect -a isaiah@singlebrook.com
gem owner adobe_connect -a leon@singlebrook.com

**Comment by zachpendleton** [comment]
I was able to add Leon, but I'm getting an "Adding isaiah@singlebrook.com:
Owner could not be found" message when trying to add Isaiah. Can you verify
that he's got that email set up w/ Rubygems?

**Comment by Rodel30** [comment]
The email I use at that site is codingcyborg@gmail.com, sorry for the confusion!

**Comment by zachpendleton** [comment]
Great, thanks. You've been added as an owner to the gem.

**Comment by sbleon** [comment]
Thanks, Zach! I just released 1.0.4 :-)

**Pull request merged**
